export enum ApplicationStatusTypeEnum {
  APPLIED = 'APPLIED',
  SCREENING = 'SCREENING',
  CODE_ASSESSMENT = 'CODE_ASSESSMENT',
  INTERVIEWING = 'INTERVIEWING',
  REJECTED = 'REJECTED',
  UNKNOWN = 'UNKNOWN'
}
