export enum InterviewTypeEnum {
  INITIAL_SCREEN = 'INITIAL_SCREEN',
  CODING_ASSESSMENT = 'CODING_ASSESSMENT',
  FIRST_INTERVIEW = 'FIRST_INTERVIEW',
  TECHNICAL_INTERVIEW = 'TECHNICAL_INTERVIEW',
  FINAL_INTERVIEW = 'FINAL_INTERVIEW',
  MIDDLE_INTERVIEW = 'MIDDLE_INTERVIEW'
}
